package com.taboia872.androidassist.ui.theme

import androidx.compose.ui.graphics.Color

// Teal palette — same scheme the original IA Assistant uses, so both apps
// feel identical side by side.
val AILightPrimary = Color(0xFF006A6A)
val AILightOnPrimary = Color(0xFFFFFFFF)
val AILightPrimaryContainer = Color(0xFF9CF1F0)
val AILightOnPrimaryContainer = Color(0xFF002020)
val AILightSecondary = Color(0xFF4A6363)
val AILightOnSecondary = Color(0xFFFFFFFF)
val AILightSecondaryContainer = Color(0xFFCCE8E7)
val AILightOnSecondaryContainer = Color(0xFF051F1F)
val AILightTertiary = Color(0xFF5B5B7E)
val AILightOnTertiary = Color(0xFFFFFFFF)
val AILightTertiaryContainer = Color(0xFFE2DFFF)
val AILightOnTertiaryContainer = Color(0xFF181837)
val AILightBackground = Color(0xFFFAFDFC)
val AILightOnBackground = Color(0xFF191C1C)
val AILightSurface = Color(0xFFFAFDFC)
val AILightOnSurface = Color(0xFF191C1C)
val AILightSurfaceVariant = Color(0xFFDAE5E4)
val AILightOnSurfaceVariant = Color(0xFF3F4948)
val AILightOutline = Color(0xFF6F7978)
val AILightError = Color(0xFFB3261E)
val AILightOnError = Color(0xFFFFFFFF)
val AILightErrorContainer = Color(0xFFF9DEDC)
val AILightOnErrorContainer = Color(0xFF601410)

val AIDarkPrimary = Color(0xFF80D5D4)
val AIDarkOnPrimary = Color(0xFF003737)
val AIDarkPrimaryContainer = Color(0xFF004F4F)
val AIDarkOnPrimaryContainer = Color(0xFF9CF1F0)
val AIDarkSecondary = Color(0xFFB0CCCB)
val AIDarkOnSecondary = Color(0xFF1C3534)
val AIDarkSecondaryContainer = Color(0xFF334B4B)
val AIDarkOnSecondaryContainer = Color(0xFFCCE8E7)
val AIDarkTertiary = Color(0xFFC4C3EA)
val AIDarkOnTertiary = Color(0xFF2D2D4D)
val AIDarkTertiaryContainer = Color(0xFF444465)
val AIDarkOnTertiaryContainer = Color(0xFFE2DFFF)
val AIDarkBackground = Color(0xFF101414)
val AIDarkOnBackground = Color(0xFFE0E3E2)
val AIDarkSurface = Color(0xFF101414)
val AIDarkOnSurface = Color(0xFFE0E3E2)
val AIDarkSurfaceVariant = Color(0xFF3F4948)
val AIDarkOnSurfaceVariant = Color(0xFFBEC9C8)
val AIDarkOutline = Color(0xFF899392)
val AIDarkError = Color(0xFFF2B8B5)
val AIDarkOnError = Color(0xFF601410)
val AIDarkErrorContainer = Color(0xFF8C1D18)
val AIDarkOnErrorContainer = Color(0xFFF9DEDC)
